// this file was generated by serverless-auto-swagger
            module.exports = {
  "swagger": "2.0",
  "info": {
    "title": "authentication-lambda",
    "version": "1"
  },
  "paths": {
    "/authentication/register": {
      "post": {
        "summary": "register",
        "description": "",
        "operationId": "register.post./authentication/register",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [],
        "responses": {
          "200": {
            "description": "200 response"
          }
        }
      }
    },
    "/authentication/login": {
      "post": {
        "summary": "login",
        "description": "",
        "operationId": "login.post./authentication/login",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [],
        "responses": {
          "200": {
            "description": "200 response"
          }
        }
      }
    },
    "/getusers": {
      "get": {
        "summary": "getUsers",
        "description": "",
        "operationId": "getUsers.get./getusers",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [],
        "responses": {
          "200": {
            "description": "200 response"
          }
        }
      }
    },
    "/": {
      "get": {
        "summary": "hello",
        "description": "",
        "operationId": "hello.get./",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [],
        "responses": {
          "200": {
            "description": "200 response"
          }
        }
      }
    }
  },
  "definitions": {},
  "securityDefinitions": {}
};